// VueDemo/component-ex-1/src/components/Parent.vue
<template>
    <child :app-title="'My App'" @clickTitle="onTitleClicked($event)"/>
</template>

<script>
    import Child from "./Child";
    export default {
        name: "Parent",
        components: {Child},
        methods: {
            onTitleClicked(title) {
                alert(`Title clicked: ${title}`)
            }
        },
    }
</script>

<style scoped>

</style>

// ReactDemo/dataflow-ex/src/Parent.jsx
import React, {Component} from 'react';
import Child from "./Child";


export default class Parent extends Component {
    render() {
        return (
            <Child appTitle={'My App'}
                   clickTitle={(title) =>
                       this.onTitleClicked(title)}/>
        );
    }

    onTitleClicked(title) {
        alert(`Title clicked: ${title}`);
    }
}
